### ISSUE TITLE
Plugin does not work with Istio v1.0

### ISSUE THREAD

**Issue by graziergeek** [open-policy-agent/opa-istio-plugin#44]
I'm not having any success going thru the quick start.

Seems like a couple of issues:
1) mixer config - when I bounce pilot after the configmap change, it's unable to start.
2) sidecar injection - after I label my app NS to enable opa-istio-injection, deploying bookinfo, all pods stay in a perpetual state of init.

Has anyone tried this with Istio 1.0?

Thanks

**Comment by graziergeek** [comment]
This change to step 2 in the quick start fixes the pilot bounce problem (note the match til '\n' char):
`kubectl -n istio-system \
    replace configmap istio \
    -f <(kubectl -n istio-system get configmap istio -o yaml \
            | sed 's/mixerCheckServer: .*\\n/mixerCheckServer: localhost:50051\\n/g')
`

The old replace produced this in the configmap:
`mixerCheckServer: localhost:50051 istio-telemetry.istio-system.svc.cluster.local:9091\n`

**Comment by ashutosh-narkar** [comment]
@graziergeek Thanks for fixing the first problem. I am trying out the tutorial with Istio 1.0.

**Comment by graziergeek** [comment]
@ashutosh-narkar , thanks for looking into it.  I understand that Istio is moving RBAC checking from Mixer to Envoy.  I wonder if OPA agent could be configured that way too (as opposed to its own separate sidecar).  We are also looking at the OPA Mixer Adapter config too.  Personally, I'd rather see checking done in the sidecar tho.

Let me know if I can help -- test or whatever.  Thanks again.

**Comment by tsandall** [comment]
It does not look like it's possible to reconfigure Istio to direct Check requests to a different API endpoint. However, with Istio v1.0 it seems like it's possible to install Envoy filters programatically. We can update the plugin to implement the Envoy ext_authz API and update the quick start steps to rely on Envoy filters instead of reconfiguring Istio itself.
