### ISSUE TITLE
Should the plugin work with Istio 0.8?

### ISSUE THREAD

**Issue by bluecamel** [open-policy-agent/opa-istio-plugin#47]
We've been unable to get quick start to work with Istio 0.8.  opa-istio is listening, so the issue seems to be with making Istio use that for checks.

The quick start docs include a broken link to https://istio.io/docs/reference/config/istio.mesh.v1alpha1.html#MeshConfig

I can only guess that that pointed to the 0.7 docs: https://archive.istio.io/v0.7/docs/reference/config/istio.mesh.v1alpha1.html#MeshConfig

Any advice on how to get this to work on 0.8 or is there a recommended version?

**Comment by ashutosh-narkar** [comment]
@bluecamel Thanks for filing the issue. Yes the broken link was to the 0.7 docs which was the last version we tested the plugin with. We are working on getting the plugin to work with Istio 1.0 as described in https://github.com/open-policy-agent/opa-istio-plugin/issues/44.

**Comment by bluecamel** [comment]
@ashutosh-narkar Thanks so much for the info.  We'll give it a go with 0.7.
