### ISSUE TITLE
Inject Sidecar per Pod

### ISSUE THREAD

**Issue by tommyJimmy87** [open-policy-agent/opa-istio-plugin#59]
Would be nice to have the injection with the annotations. Like in Istio you can define the injection for namespace or per pod with the annotation : `sidecar.istio.io/inject: "true"`

**Comment by tsandall** [comment]
The quickstart.yaml file shows how you can enable OPA sidecar injection. https://github.com/open-policy-agent/opa-istio-plugin/blob/master/quick_start.yaml. The example injects OPA into pods in namespaces labeled with `opa-istio-injection=enabled`. If you wanted finer-grained injection, you could customize the mutating admission control policy (or write you own like in that file.)

Let me know if this does not answer your question.
