### ISSUE TITLE
Proto constraint validation failed (ExtAuthzValidationError.StatPrefix

### ISSUE THREAD

**Issue by MandarJKulkarni** [open-policy-agent/opa-istio-plugin#61]
I have installed opa-istio-plugin in one of my app's deployments and it is not working. 
I have used the same quick_start.yaml but the gateway to my service is not working.
There is nothing in the logs of opa-istio or my app.
But in the istio-proxy's log, I see below error.

 severity:  "ERROR"  
 textPayload:  "[2018-12-13 18:53:25.553][11][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 10.16.3.8_8080: Proto constraint validation failed (ExtAuthzValidationError.StatPrefix: ["value length must be at least " '\x01' " bytes"]): grpc_service {

Istio 1.0.4
Kubectl version 
   Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3"
   Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5"

**Also, if I delete the envoyfilter ext-authz and then the app works.**

**Comment by tsandall** [comment]
This looks like incompatibility between the gRPC client in Envoy and the server in OPA-Istio. @ashutosh-narkar can you take a look? We’ll have to try to reproduce this using the same versions.

**Comment by tsandall** [comment]
It’s referred to inside the EnvoyFilter object defined in the quick start.

**Comment by MandarJKulkarni** [comment]
sorry, I had realized that and hence tried running the same scenario after removing the filter.
But I meant to ask, how it is breaking the code, is it something to do with my gateway, virtualservice or deployment?

**Comment by MandarJKulkarni** [comment]
@ashutosh-narkar , @tsandall any comments? is there some workaround that I can try?

**Comment by ashutosh-narkar** [comment]
I can try this out tomorrow and get back to you.

**Comment by ashutosh-narkar** [comment]
Sorry about the delay @MandarJKulkarni. I did not get a chance to try this out with your specific version. Are you blocked on this ?

**Comment by MandarJKulkarni** [comment]
Kind of...

**Comment by MandarJKulkarni** [comment]
I tried this today with Istio 1.0.5 and faced the same problem.
**The plugin works with sample bookinfo application.
But not for my app.**

I created same routes (productpage and api/v1/products) for my app as well to make sure I can use the same opa-policy, but the error with envoyfilter remains. 
And again, I was able to access my app through istio gateway after I removed the envoy filter ext-authz and redeployed my app.

**Comment by ashutosh-narkar** [comment]
Hello @MandarJKulkarni , I apologize for the delayed response. Can you share your app and details about how to deploy it ?  Also are there any other relevant logs you can share. 

I can try with a different app and see if I can re-create the issue.

**Comment by MandarJKulkarni** [comment]
I have a repository https://github.com/MandarJKulkarni/docker_flask_kubernetes
Where my sample app code is present.

The readme has commands to build docker image and deploy on kubernetes.
I am deploying in a Google Cloud project's kubernetes cluster.  
After I install Istio in the cluster, I expose the deployment as a clusterIP 

kubectl expose deployment flaskapp --type=ClusterIP --port 8080 --target-port 8080 

and access the app through istio ingress gateway.

**Comment by MandarJKulkarni** [comment]
![image](https://user-images.githubusercontent.com/33712629/50514439-37f23a00-0ac4-11e9-92ab-1d6831b0d926.png)

This is what I saw in the log for istio-proxy for my app.

The opa-istio log says
" level=info msg="Starting gRPC server." addr=":9191" query=data.istio.authz.allow"
"level=info msg="First line of log stream." addrs="[:8181]" insecure_addr="

**Comment by MandarJKulkarni** [comment]
![image](https://user-images.githubusercontent.com/33712629/50514533-c9fa4280-0ac4-11e9-8755-9dc43e02e929.png)

I have put these error messages from the log in the issue description as well.

**Comment by MandarJKulkarni** [comment]
> Hello @MandarJKulkarni , I apologize for the delayed response. Can you share your app and details about how to deploy it ? Also are there any other relevant logs you can share.
> 
> I can try with a different app and see if I can re-create the issue.

@ashutosh-narkar , did you get a chance to try this out with a different app?

**Comment by ashutosh-narkar** [comment]
Hello @MandarJKulkarni  was out for the holidays. Will try this today and update.

**Comment by ashutosh-narkar** [comment]
@MandarJKulkarni when you create a service using the below command, the port is **unset**.
```bash
kubectl expose deployment flaskapp --type=ClusterIP --port 8080 --target-port 8080

kubectl describe svc flaskapp
Name:              flaskapp
Namespace:         default
Labels:            run=flaskapp
Annotations:       <none>
Selector:          run=flaskapp
Type:              ClusterIP
IP:                10.102.249.23
Port:              <unset>  8080/TCP
TargetPort:        8080/TCP
Endpoints:         172.17.0.20:8080
Session Affinity:  None
Events:            <none>
```
I created  a service using the below definition: 
**flask-productpage-svc.yml**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    run: flaskapp
spec:
  ports:
  - port: 8080
    name: http
  selector:
    run: flaskapp
```
```bash
kubectl apply -f flask-productpage-svc.yml

kubectl describe svc flaskapp
Name:              flaskapp
Namespace:         default
Labels:            run=flaskapp
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"flaskapp"},"name":"flaskapp","namespace":"default"},"spec":{"ports":[...
Selector:          run=flaskapp
Type:              ClusterIP
IP:                10.109.245.37
Port:              http  8080/TCP
TargetPort:        8080/TCP
Endpoints:         172.17.0.20:8080
Session Affinity:  None
Events:            <none>
```

Notice the port is no longer **unset** and now has a name. With this you won't get the validation error.

**Comment by MandarJKulkarni** [comment]
Hi @ashutosh-narkar , this was it! I tried this with deployment using the yml file and it worked as expected for me.
Thank you very much for troubleshooting the issue (which apparently is not with your plugin, but with kubectl config) and my apologies for the trouble caused.

**Comment by ashutosh-narkar** [comment]
@MandarJKulkarni no problem !
