### ISSUE TITLE
Add tagging to this repository

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa-istio-plugin#79]
While we currently track upstream OPA stable releases, we don't have tags set up on this repo. This makes it hard for users that want to build from source and track stable versions. We should update the vendoring update automation to tag the repository.

Also, I noticed that the automation is leaving branches around. Is there anyway we can avoid this?

**Comment by ashutosh-narkar** [comment]
We tag the repo manually while merging the automated pull requests. Also branches created by the automation are deleted during merge.
