### ISSUE TITLE
Will this plugin work with vanilla envoy ext_authz filter?

### ISSUE THREAD

**Issue by danielpops** [open-policy-agent/opa-istio-plugin#84]
In my environment we are not using kubernetes or istio, but we are using envoy and want to use OPA for authorization. The README in this repo refers to istio and kubernetes, but I wonder if there is any hard dependency on istio or kubernetes or if this can be used with envoy ext_authz alone.

thanks!

**Comment by ashutosh-narkar** [comment]
Hello @danielpops , Envoy's external authorization filter calls OPA for authorization decisions. There is no hard dependency on istio or kubernetes. For example, you can deploy your envoy co-located  services and OPA using docker-compose and then configure the proxy to use OPA. 

We are working on an example showing how the OPA-Envoy integration can work and it should be out next week.

**Comment by ashutosh-narkar** [comment]
@danielpops here is an example of OPA-Envoy ext authz https://github.com/ashutosh-narkar/opa-envoy-ext-authz. 

The example is a WIP.

**Comment by danielpops** [comment]
Amazing! Thanks for confirming, and thanks for the quick response!
