### ISSUE TITLE
Add preprocessed path to input

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa-istio-plugin#92]
It would be useful to have the supplied as a string array so that policy authors can pattern match:

```
allow {
   input.parsed_path = ["widgets", id, "execute"]
}
```

This will help with indexing as well: https://www.openpolicyagent.org/docs/latest/faq/#high-performance-policy-decisions

**Comment by ashutosh-narkar** [comment]
See https://github.com/open-policy-agent/opa/issues/1507
